package form;

/**
 *
 * @author oyeaaa
 */
public class formTentangKami extends javax.swing.JInternalFrame {

    /**
     * Creates new form formTentangKita
     */
    public formTentangKami() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        fotoRifqi = new javax.swing.JLabel();
        lblRifqiPratama = new javax.swing.JLabel();
        lblNimRifqi = new javax.swing.JLabel();
        fotoAdit = new javax.swing.JLabel();
        lblAdit = new javax.swing.JLabel();
        lblNimAdit = new javax.swing.JLabel();
        fotoLuthfi = new javax.swing.JLabel();
        lblLuthfi = new javax.swing.JLabel();
        lblNimLuthfi = new javax.swing.JLabel();
        fotoNovel = new javax.swing.JLabel();
        lblNovel = new javax.swing.JLabel();
        lblNimNovel = new javax.swing.JLabel();
        fotoRafi = new javax.swing.JLabel();
        lblRafi = new javax.swing.JLabel();
        lblNimRafi = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 632));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("KELOMPOK PERPUSTAKAAN - IF 8");
        lblTitle.setPreferredSize(new java.awt.Dimension(1366, 43));

        fotoRifqi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rifqi.png"))); // NOI18N

        lblRifqiPratama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRifqiPratama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRifqiPratama.setText("RIFQI PRATAMA J");

        lblNimRifqi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNimRifqi.setText("10118322");

        fotoAdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adit.png"))); // NOI18N

        lblAdit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAdit.setText("ADITTYA KAMAL");

        lblNimAdit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNimAdit.setText("10118337");

        fotoLuthfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luthfi.png"))); // NOI18N

        lblLuthfi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLuthfi.setText("LUTHFI RIFQI Z");

        lblNimLuthfi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNimLuthfi.setText("10118312");

        fotoNovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/novel.png"))); // NOI18N

        lblNovel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNovel.setText("MUHAMMAD NOVEL Z");

        lblNimNovel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNimNovel.setText("10118348");

        fotoRafi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rafi.png"))); // NOI18N

        lblRafi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRafi.setText("M. RAFI AVISINA");

        lblNimRafi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNimRafi.setText("10118328");

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRifqiPratama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(lblAdit)
                        .addGap(111, 111, 111)
                        .addComponent(lblLuthfi)
                        .addGap(102, 102, 102)
                        .addComponent(lblNovel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoRifqi)
                        .addGap(60, 60, 60)
                        .addComponent(fotoAdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(fotoLuthfi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(fotoNovel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fotoRafi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRafi)
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblNimRifqi)
                .addGap(186, 186, 186)
                .addComponent(lblNimAdit)
                .addGap(170, 170, 170)
                .addComponent(lblNimLuthfi)
                .addGap(188, 188, 188)
                .addComponent(lblNimNovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNimRafi)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoRifqi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoAdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoLuthfi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoNovel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoRafi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRifqiPratama)
                    .addComponent(lblAdit)
                    .addComponent(lblLuthfi)
                    .addComponent(lblNovel)
                    .addComponent(lblRafi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNimRifqi)
                    .addComponent(lblNimAdit)
                    .addComponent(lblNimLuthfi)
                    .addComponent(lblNimNovel)
                    .addComponent(lblNimRafi))
                .addContainerGap(781, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel fotoAdit;
    private javax.swing.JLabel fotoLuthfi;
    private javax.swing.JLabel fotoNovel;
    private javax.swing.JLabel fotoRafi;
    private javax.swing.JLabel fotoRifqi;
    private javax.swing.JLabel lblAdit;
    private javax.swing.JLabel lblLuthfi;
    private javax.swing.JLabel lblNimAdit;
    private javax.swing.JLabel lblNimLuthfi;
    private javax.swing.JLabel lblNimNovel;
    private javax.swing.JLabel lblNimRafi;
    private javax.swing.JLabel lblNimRifqi;
    private javax.swing.JLabel lblNovel;
    private javax.swing.JLabel lblRafi;
    private javax.swing.JLabel lblRifqiPratama;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
